(()=>{
const t={
en:{skip:"Skip to main content",navAbout:"About",navProjects:"Projects",navVision:"Future vision",navContact:"Contact",heroTag:"Taiwan · Independent software development",heroHeading1:"Practical software today,",heroHeading2:"smarter living tomorrow.",heroLead:"YuChen Home develops and maintains useful applications today while exploring smart-home platforms, device integration, and more reliable digital experiences for the future.",explore:"Explore projects",direction:"Future direction",heroCaption:"Independently developed · Always learning, designing and building",aboutKicker:"About",aboutTitle:"Building through real products, laying the groundwork for what's next.",aboutParagraph:"YuChen Home is an early-stage independent software initiative in Taiwan. I currently design, develop, and maintain practical applications, using experience in software and systems integration as the foundation for future smart-home work.",originLabel:"Brand milestone",originDetail:"Domain registration date for yuchenhome.net, recorded as an early brand milestone.",originNote:"YuChen Home is an independent software initiative that has not yet been legally incorporated. This is not a company incorporation date.",value1Title:"Continuous development",value1Text:"Learning through shipped software, version updates, and ongoing maintenance.",value2Title:"Reliability first",value2Text:"Focusing on user experience, stability, and long-term maintainability.",projectsKicker:"Current work",projectsTitle:"Starting with the tools we build.",projectsSub:"An example of currently available software development work.",projectStatus:"Actively developed and maintained",projectDesc:"A native macOS menu bar app that brings battery health, network traffic, and system performance into one streamlined interface, helping people understand their devices.",viewGithub:"View on GitHub",visionKicker:"Future vision",visionTitle:"Making smart homes easier to connect, manage, and maintain.",visionNote:"These are future areas of exploration. No commercial smart-home platform has launched yet.",vision1Title:"Device and system integration",vision1Desc:"Exploring how different smart-home devices and systems can work better together.",vision2Title:"Centralized management",vision2Desc:"Exploring intuitive interfaces for device status, monitoring, and control.",vision3Title:"Long-term reliability",vision3Desc:"Designing with maintenance, stability, and continuous improvement in mind.",futureLabel:"Planned direction",contactKicker:"Connect",contactTitle:"Let's explore the next idea.",contactBody:"Follow ongoing projects and discuss product ideas or technical questions on GitHub.",contactButton:"Visit GitHub",footerNote:"Taiwan · Independent software initiative",backTop:"Back to top ↑"},
zh:{skip:"跳到主要內容",navAbout:"關於",navProjects:"開發專案",navVision:"未來方向",navContact:"聯絡",heroTag:"台灣・獨立軟體開發品牌",heroHeading1:"專注當下的實用軟體，",heroHeading2:"連接未來的智慧生活。",heroLead:"YuChen Home 從應用程式開發與維護起步，逐步探索智慧家居平台、設備整合與更可靠的數位生活體驗。",explore:"探索開發專案",direction:"未來發展方向",heroCaption:"獨立開發中 · 持續學習、設計與實作",aboutKicker:"關於我們",aboutTitle:"以產品實作累積技術，為下一個階段打好基礎。",aboutParagraph:"YuChen Home 是由台灣獨立開發者經營的早期軟體開發品牌，目前持續設計、開發與維護實用型應用程式。我們將既有的軟體與系統整合經驗，作為未來投入智慧家居技術的基礎。",originLabel:"品牌起始紀錄",originDetail:"yuchenhome.net 網域註冊日，作為品牌籌備歷程的參考。",originNote:"YuChen Home 目前為個人經營的開發品牌，尚未完成公司登記；此日期並非正式公司設立日期。",value1Title:"持續開發",value1Text:"以實際產品、版本更新與維護累積經驗。",value2Title:"重視可靠性",value2Text:"關注使用體驗、穩定性與長期可維護性。",projectsKicker:"開發中的產品",projectsTitle:"從正在打造的工具開始。",projectsSub:"以下是目前的公開軟體開發成果。",projectStatus:"持續開發與維護",projectDesc:"原生 macOS 選單列工具，將電池健康度、網路流量與系統效能資訊集中於簡潔介面，協助使用者更清楚地了解自己的裝置。",viewGithub:"查看 GitHub 專案",visionKicker:"未來願景",visionTitle:"讓智慧家居更容易連接、管理與維護。",visionNote:"以下是未來探索中的發展方向，尚未推出正式智慧家居平台產品。",vision1Title:"設備與系統整合",vision1Desc:"研究讓不同智慧設備更順暢地協同運作的方式。",vision2Title:"集中化管理體驗",vision2Desc:"探索直覺、清晰的裝置狀態監控與控制介面。",vision3Title:"長期維護與可靠性",vision3Desc:"把可維護性、穩定性與持續改善納入產品設計。",futureLabel:"規劃方向",contactKicker:"合作與交流",contactTitle:"一起探索下一個好點子。",contactBody:"歡迎關注我們的開發成果，透過 GitHub 交流產品想法與技術問題。",contactButton:"前往 GitHub",footerNote:"Taiwan · Independent software initiative",backTop:"回到頁首 ↑"}
};
const b=document.getElementById('langToggle');
const setLanguage=(lang)=>{const d=t[lang]||t.zh;document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(d[key])el.textContent=d[key]});document.documentElement.lang=lang==='en'?'en':'zh-Hant';if(b){b.innerHTML=(lang==='en'?'繁中':'EN')+' <span aria-hidden="true">↗</span>';b.setAttribute('aria-label',lang==='en'?'切換為繁體中文':'Switch to English')}try{localStorage.setItem('ych-language',lang)}catch(_){} };
let saved;try{saved=localStorage.getItem('ych-language')}catch(_){}setLanguage(saved==='en'?'en':'zh');
if(b)b.addEventListener('click',()=>setLanguage(document.documentElement.lang==='en'?'zh':'en'));
const year=document.getElementById('year');if(year)year.textContent=new Date().getFullYear();
})();